#
# MIT License
#
# (C) Copyright 2019,2021-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
# Install a Cray CA certificate onto a SLES system.

- name: Check for the existence of certificate_authority.crt
  stat:
    path: "{{ ca_cert_file }}"
  register: cert_file

- name: Copy CA certificate to the canonical location
  copy:
    src: "{{ ca_cert_file }}"
    dest: "{{ ca_cert_dest_dir }}"
    remote_src: yes
  when: cert_file.stat.exists

# NOTE: Only run this in SLES 15 SP2, since the version in SLES 15 SP3
# doesn't work in a chrooted environment.
- name: Update the certificate
  command: update-ca-certificates
  when: >
    ansible_distribution_file_variety == "SUSE" and
    ansible_distribution_version == "15.2" and
    cert_file.stat.exists


# In SLES 15 SP3/SP4, run the certificate update scripts directly
- name: Find certificate update scripts
  find:
    paths:
    - /etc/ca-certificates/update.d
    - /usr/lib/ca-certificates/update.d
    patterns:
    - '*.run'
  register: ca_scripts
  when: >
    ansible_distribution_file_variety == "SUSE" and
    ansible_distribution_version != "15.2" and
    cert_file.stat.exists


- name: Run certificate update scripts
  command: "{{ item.path }}"
  loop: "{{ ca_scripts.files }}"
  when: >
    ansible_distribution_file_variety == "SUSE" and
    ansible_distribution_version != "15.2" and
    cert_file.stat.exists
