#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
- name: Add zone prefix to node to zone mapping
  script: "add_k8s_zone_prefix.py '{{ k8s_zone_prefix | default('') }}'"
  args:
    executable: python3
  register: k8s_mapping_generation
  delegate_to: "{{ play_hosts | first }}"
  run_once: true
  changed_when: false

- name: Parse node to zone mapping
  set_fact:
    node_zone_mapping: "{{ (k8s_mapping_generation.stdout | default('{}', true)) | from_json }}"
  delegate_to: "{{ play_hosts | first }}"
  run_once: true

- name: Apply k8s topology zone labels to nodes
  kubernetes.core.k8s:
    api_version: v1
    kind: Node
    name: "{{ item.key }}"
    definition:
      metadata:
        labels:
          topology.kubernetes.io/zone: "{{ item.value }}"
  loop: "{{ node_zone_mapping | dict2items }}"
  delegate_to: "{{ play_hosts | first }}"
  run_once: true
  when: 
    - node_zone_mapping is defined
    - node_zone_mapping | length > 0
